### ISSUE TITLE
Flesh out all products view

### ISSUE THREAD

**Issue by chtakahashi** [2008-Object-keys-twin/Grace-Flopper#18]
- [x] make each product a basic card with maybe name, image, and an add to cart button (does not have to be connected yet
- [ ] clicking into a card will eventually show the single product view, does not need to be connected yet

**Comment by chtakahashi** [comment]
changing jobs and doing a bit of cleanup and found these issues were still open :) hope you're all doing well! @BigMikeM @amadiw

**Comment by BigMikeM** [comment]
Woooow what a blast from the past! Thanks for cleaning it up lol.

Hope y'all are doing well these days and that this job change of yours is a
good thing! I'm still doing my thing at Chase with no plans to move any
time soon.
